//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradebookOnlineApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class projekty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public projekty()
        {
            this.etapy = new HashSet<etapy>();
            this.oceny_projektow = new HashSet<oceny_projektow>();
            this.studenci = new HashSet<studenci>();
        }
    
        public int id_proj { get; set; }
        public Nullable<int> id_prow { get; set; }
        public Nullable<int> id_zajec { get; set; }
        public string nazwa_proj { get; set; }
        public Nullable<System.DateTime> termin_wyk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<etapy> etapy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oceny_projektow> oceny_projektow { get; set; }
        public virtual prowadzacy prowadzacy { get; set; }
        public virtual zajecia zajecia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studenci> studenci { get; set; }
    }
}
