//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradebookOnlineApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class studenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public studenci()
        {
            this.oceny_etapow = new HashSet<oceny_etapow>();
            this.oceny_projektow = new HashSet<oceny_projektow>();
            this.projekty = new HashSet<projekty>();
            this.zajecia = new HashSet<zajecia>();
        }
    
        public int id_student { get; set; }
        public Nullable<int> id_grupy { get; set; }
        public string nr_album { get; set; }
        public string imie_student { get; set; }
        public string drugie_imie_student { get; set; }
        public string nazwisko_student { get; set; }
        public System.DateTime data_urodzenia_student { get; set; }
        public string miejsce_urodzenia_student { get; set; }
        public string pesel_student { get; set; }
        public string email_student { get; set; }
        public string telefon_student { get; set; }
    
        public virtual grupy_dziekanskie grupy_dziekanskie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oceny_etapow> oceny_etapow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oceny_projektow> oceny_projektow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projekty> projekty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zajecia> zajecia { get; set; }
    }
}
